package com.ernkebe.entities.grouping;

// default package
// Generated May 6, 2014 8:11:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.List;

/**
 * Article generated by hbm2java
 */
public class CarrotArticle implements java.io.Serializable {

	
	private Integer id;
	private Integer articleId;
	private Integer carrotCategoryId;

	public CarrotArticle() {
	}

	public CarrotArticle(Integer articleId, Integer carrotCategoryId) {
		this.articleId = articleId;
		this.carrotCategoryId = carrotCategoryId;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getArticleId() {
		return articleId;
	}

	public void setArticleId(Integer articleId) {
		this.articleId = articleId;
	}

	public Integer getCarrotCategoryId() {
		return carrotCategoryId;
	}

	public void setCarrotCategoryId(Integer carrotCategoryId) {
		this.carrotCategoryId = carrotCategoryId;
	}


}
