package com.ernkebe.entities.grouping;
// Generated Oct 4, 2014 9:44:00 PM by Hibernate Tools 3.4.0.CR1

/**
 * CommonWords generated by hbm2java
 */
public class KmeansUncommonStemWords implements java.io.Serializable {

	public static final String FIELD_ARTICLE_ID = "articleId";
	private Integer id;
	private Integer articleId;
	private Integer centroid;

	public KmeansUncommonStemWords() {
	}

	public KmeansUncommonStemWords(Integer articleId, Integer centroid) {
		this.articleId = articleId;
		this.centroid = centroid;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getArticleId() {
		return articleId;
	}

	public void setArticleId(Integer articleId) {
		this.articleId = articleId;
	}

	public Integer getCentroid() {
		return centroid;
	}

	public void setCentroid(Integer centroid) {
		this.centroid = centroid;
	}


}
