package com.ernkebe.entities.initial;


// Generated May 6, 2014 8:11:34 PM by Hibernate Tools 3.4.0.CR1

/**
 * ArticleCategories generated by hbm2java
 */
public class ArticleCategories implements java.io.Serializable {

	private Integer id;
	private int articleId;
	private int categoryId;
	
	private ProvidedCategories category;

	public static String FIELD_ARTICLE_ID = "articleId";
	public static String FIELD_CATEGORIE_ID = "categoryId";
	
	public ArticleCategories() {
	}

	public ArticleCategories(int articleId, int categoryId) {
		this.articleId = articleId;
		this.categoryId = categoryId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getArticleId() {
		return this.articleId;
	}

	public void setArticleId(int articleId) {
		this.articleId = articleId;
	}

	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	public ProvidedCategories getCategory() {
		return category;
	}

	public void setCategory(ProvidedCategories category) {
		this.category = category;
	}

}
