package com.ernkebe.entities.initial;

// default package
// Generated May 6, 2014 8:11:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.List;

import com.ernkebe.entities.ArticlesUncommonWords;
import com.ernkebe.entities.ArticlesUncommonWordsStem;

/**
 * Article generated by hbm2java
 */
public class Article implements java.io.Serializable {

	
	public static final String FIELD_ID = "articleId";
	private Integer articleId;
	private String title;
	private String link;
	private String description;
	private Date pubDate;
	private Date updateDate;
	private int siteId;
	private String fullText;
	private Integer wordsCount;
	
	private List<String> catList;
	
	private List categories; 
	private ArticlesUncommonWords uncommonWords;
	private ArticlesUncommonWordsStem uncommonWordsStem;
	
	public static String FIELD_TITLE = "title";
	public static String FIELD_WORDS_COUNT = "wordsCount";
	public static String FIELD_ARTICLE_ID = "articleId";
	public static String FIELD_PUB_DATE = "pubDate";
	
	private String titleS;

	public Article() {
	}

	public Article(String title, int siteId) {
		this.title = title;
		this.siteId = siteId;
	}

	public Article(String title, String link, String description, Date pubDate,
			Date updateDate, int siteId, String fullText, Integer wordsCount) {
		this.title = title;
		this.link = link;
		this.description = description;
		this.pubDate = pubDate;
		this.updateDate = updateDate;
		this.siteId = siteId;
		this.fullText = fullText;
		this.wordsCount = wordsCount;
	}

	public Integer getArticleId() {
		return this.articleId;
	}

	public void setArticleId(Integer articleId) {
		this.articleId = articleId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getPubDate() {
		return this.pubDate;
	}

	public void setPubDate(Date pubDate) {
		this.pubDate = pubDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public int getSiteId() {
		return this.siteId;
	}

	public void setSiteId(int siteId) {
		this.siteId = siteId;
	}

	public String getFullText() {
		return this.fullText;
	}

	public void setFullText(String fullText) {
		this.fullText = fullText;
	}

	public List getCategories() {
		return categories;
	}

	public void setCategories(List categories) {
		this.categories = categories;
	}

	public List<String> getCatList() {
		return catList;
	}

	public void setCatList(List<String> catList) {
		this.catList = catList;
	}

	public ArticlesUncommonWords getUncommonWords() {
		return uncommonWords;
	}

	public void setUncommonWords(ArticlesUncommonWords uncommonWords) {
		this.uncommonWords = uncommonWords;
	}

	public ArticlesUncommonWordsStem getUncommonWordsStem() {
		return uncommonWordsStem;
	}

	public void setUncommonWordsStem(ArticlesUncommonWordsStem uncommonWordsStem) {
		this.uncommonWordsStem = uncommonWordsStem;
	}

	public Integer getWordsCount() {
		return wordsCount;
	}

	public void setWordsCount(Integer wordsCount) {
		this.wordsCount = wordsCount;
	}

	public String getTitleS() {
		return articleId + " "+ title;
	}

	public void setTitleS(String titleS) {
		this.titleS = titleS;
	}
}
