package com.ernkebe.entities.initial;

// Generated May 6, 2014 8:11:34 PM by Hibernate Tools 3.4.0.CR1

/**
 * ProvidedCategories generated by hbm2java
 */
public class ProvidedCategories implements java.io.Serializable {

	private Integer id;
	private String category;

	public static String FIELD_CATEGORY	= "category";
	public ProvidedCategories() {
	}

	public ProvidedCategories(String category) {
		this.category = category;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

}
