package com.ernkebe.entities.newsWords;
// Generated Oct 4, 2014 9:44:00 PM by Hibernate Tools 3.4.0.CR1

/**
 * CommonWords generated by hbm2java
 */
public class ArticleNewsWordsStem implements java.io.Serializable {

	private Integer id;
	private Integer articleId;
	private Integer wordId;
	private Integer frequency;

	public ArticleNewsWordsStem() {
	}

	public ArticleNewsWordsStem(Integer articleId, Integer wordId, Integer frequency) {
		this.articleId = articleId;
		this.wordId = wordId;
		this.frequency = frequency;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getFrequency() {
		return this.frequency;
	}

	public void setFrequency(Integer frequency) {
		this.frequency = frequency;
	}

	public Integer getArticleId() {
		return articleId;
	}

	public void setArticleId(Integer articleId) {
		this.articleId = articleId;
	}

	public Integer getWordId() {
		return wordId;
	}

	public void setWordId(Integer wordId) {
		this.wordId = wordId;
	}
	
}
