package com.ernkebe.entities.newsWords;
// Generated Oct 4, 2014 9:44:00 PM by Hibernate Tools 3.4.0.CR1

/**
 * CommonWords generated by hbm2java
 */
public class NewsWordsStem implements java.io.Serializable {

	private Integer id;
	private String word;

	public NewsWordsStem() {
	}

	public NewsWordsStem(String word) {
		this.word = word;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getWord() {
		return this.word;
	}

	public void setWord(String word) {
		this.word = word;
	}

}