package com.ernkebe.entities;

import java.util.Date;


// Generated Oct 4, 2014 9:44:00 PM by Hibernate Tools 3.4.0.CR1

/**
 * AnalizedDataClassifier generated by hbm2java
 */
public class AnalizedDataClassifier implements java.io.Serializable {

	private Integer id;
	private Integer freqAnalizeArticleId;
	private Date dataAnalized;

	public AnalizedDataClassifier() {
	}

	public AnalizedDataClassifier(Integer freqAnalizeArticleId, Date dateAnalized) {
		this.freqAnalizeArticleId = freqAnalizeArticleId;
		this.dataAnalized = dateAnalized;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getFreqAnalizeArticleId() {
		return this.freqAnalizeArticleId;
	}

	public void setFreqAnalizeArticleId(Integer freqAnalizeArticleId) {
		this.freqAnalizeArticleId = freqAnalizeArticleId;
	}

	public Date getDataAnalized() {
		return dataAnalized;
	}

	public void setDataAnalized(Date dataAnalized) {
		this.dataAnalized = dataAnalized;
	}

}
