package com.ernkebe.entities;
// Generated Oct 4, 2014 9:44:00 PM by Hibernate Tools 3.4.0.CR1

/**
 * CommonWords generated by hbm2java
 */
public class ArticlesUncommonWordsStem implements java.io.Serializable {

	public static final String FIELD_ARTICLE_ID = "articleId";
	private Integer id;
	private Integer articleId;
	private String uncommonStemWords;

	public ArticlesUncommonWordsStem() {
	}

	public ArticlesUncommonWordsStem(Integer articleId, String uncommonStemWords) {
		this.articleId = articleId;
		this.uncommonStemWords = uncommonStemWords;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getArticleId() {
		return articleId;
	}

	public void setArticleId(Integer articleId) {
		this.articleId = articleId;
	}

	public String getUncommonStemWords() {
		return uncommonStemWords;
	}

	public void setUncommonStemWords(String uncommonStemWords) {
		this.uncommonStemWords = uncommonStemWords;
	}

	
}
