package com.ernkebe.entities;
// Generated Oct 4, 2014 9:44:00 PM by Hibernate Tools 3.4.0.CR1

/**
 * CommonWords generated by hbm2java
 */
public class ArticlesUncommonWords implements java.io.Serializable {

	public static final String FIELD_ARTICLE_ID = "articleId";
	private Integer id;
	private Integer articleId;
	private String uncommonSimpleWords;

	public ArticlesUncommonWords() {
	}

	public ArticlesUncommonWords(Integer articleId, String uncommonSimpleWords) {
		this.articleId = articleId;
		this.uncommonSimpleWords = uncommonSimpleWords;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getArticleId() {
		return articleId;
	}

	public void setArticleId(Integer articleId) {
		this.articleId = articleId;
	}

	public String getUncommonSimpleWords() {
		return uncommonSimpleWords;
	}

	public void setUncommonSimpleWords(String uncommonSimpleWords) {
		this.uncommonSimpleWords = uncommonSimpleWords;
	}

}
