package com.ernkebe.entities;
// Generated Oct 4, 2014 9:44:00 PM by Hibernate Tools 3.4.0.CR1

/**
 * CommonWords generated by hbm2java
 */
public class CommonWords implements java.io.Serializable {

	public static final String FIELD_WORD = "word";
	public static final String FIELD_FREQUENCY = "frequency";
	private Integer id;
	private String word;
	private int frequency;

	public CommonWords() {
	}

	public CommonWords(String word, int frequency) {
		this.word = word;
		this.frequency = frequency;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getWord() {
		return this.word;
	}

	public void setWord(String word) {
		this.word = word;
	}

	public int getFrequency() {
		return this.frequency;
	}

	public void setFrequency(int frequency) {
		this.frequency = frequency;
	}

}
