package com.ernkebe.entities;

// Generated May 6, 2014 8:11:34 PM by Hibernate Tools 3.4.0.CR1

/**
 * Sites generated by hbm2java
 */
public class Sites implements java.io.Serializable {

	public static final String FIELD_NAME = "name";
	private Integer id;
	private String name;
	private String xmlUrl;
	private String siteUrl;
	private String logoImage;
	private String queryText;

	public Sites() {
	}

	public Sites(String name, String xmlUrl) {
		this.name = name;
		this.xmlUrl = xmlUrl;
	}

	public Sites(String name, String xmlUrl, String siteUrl, String logoImage,
			String queryText) {
		this.name = name;
		this.xmlUrl = xmlUrl;
		this.siteUrl = siteUrl;
		this.logoImage = logoImage;
		this.queryText = queryText;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getXmlUrl() {
		return this.xmlUrl;
	}

	public void setXmlUrl(String xmlUrl) {
		this.xmlUrl = xmlUrl;
	}

	public String getSiteUrl() {
		return this.siteUrl;
	}

	public void setSiteUrl(String siteUrl) {
		this.siteUrl = siteUrl;
	}

	public String getLogoImage() {
		return this.logoImage;
	}

	public void setLogoImage(String logoImage) {
		this.logoImage = logoImage;
	}

	public String getQueryText() {
		return this.queryText;
	}

	public void setQueryText(String queryText) {
		this.queryText = queryText;
	}
	 @Override
	    public String toString() {
	        return name;
	    }

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Sites other = (Sites) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}
	 
}
